In [2]:
#importing libraries
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import pandas as pd

In [3]:
#creating a list
a, b, c = "phd","m.tech", "b.tech"

In [5]:
d = {"categories":list("abcde"),"gender":list("mfmff"),"degree":[a,b,c,a,b], "number":[3,4,3,4,5]}
d

{'categories': ['a', 'b', 'c', 'd', 'e'],
 'gender': ['m', 'f', 'm', 'f', 'f'],
 'degree': ['phd', 'm.tech', 'b.tech', 'phd', 'm.tech'],
 'number': [3, 4, 3, 4, 5]}

In [6]:
#d = {"categories":list("abcde"),"gender":list("mfmff"),"degree":[a,b,c,a,b], "number":[3,4,3,4,5]}
data = pd.DataFrame(d)
data

categories gender  degree  number
0          a      m     phd       3
1          b      f  m.tech       4
2          c      m  b.tech       3
3          d      f     phd       4
4          e      f  m.tech       5

In [7]:
ohe = OneHotEncoder
le = LabelEncoder

# One Hot Encoding
# It is called one-hot because only one bit is "hot" or True at any time
One hot encoder cannot process tring values directly.If your nominal features are strings, then you need to first map them into integers.

pandas.get_dummies is kind of the oppoite.By defaults, it only converts tring columns into one-hot representation, unless columns are specified.  

In [8]:
data['categories']

0    a
1    b
2    c
3    d
4    e
Name: categories, dtype: object

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import numpy as np

In [11]:
#creating one hot encoder object with feature 0
#indicating the first column
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(),[0])],remainder ='passthrough')
columnTransformer.fit_transform(data)


array([[1.0, 0.0, 0.0, 0.0, 0.0, 'm', 'phd', 3],
       [0.0, 1.0, 0.0, 0.0, 0.0, 'f', 'm.tech', 4],
       [0.0, 0.0, 1.0, 0.0, 0.0, 'm', 'b.tech', 3],
       [0.0, 0.0, 0.0, 1.0, 0.0, 'f', 'phd', 4],
       [0.0, 0.0, 0.0, 0.0, 1.0, 'f', 'm.tech', 5]], dtype=object)

In [12]:
data

categories gender  degree  number
0          a      m     phd       3
1          b      f  m.tech       4
2          c      m  b.tech       3
3          d      f     phd       4
4          e      f  m.tech       5

In [14]:
np.array(columnTransformer.fit_transform(data), dtype= str)

array([['1.0', '0.0', '0.0', '0.0', '0.0', 'm', 'phd', '3'],
       ['0.0', '1.0', '0.0', '0.0', '0.0', 'f', 'm.tech', '4'],
       ['0.0', '0.0', '1.0', '0.0', '0.0', 'm', 'b.tech', '3'],
       ['0.0', '0.0', '0.0', '1.0', '0.0', 'f', 'phd', '4'],
       ['0.0', '0.0', '0.0', '0.0', '1.0', 'f', 'm.tech', '5']],
      dtype='<U6')

# Other way around by OneHot Encoder 

In [15]:
data

categories gender  degree  number
0          a      m     phd       3
1          b      f  m.tech       4
2          c      m  b.tech       3
3          d      f     phd       4
4          e      f  m.tech       5

In [29]:
encoder = OneHotEncoder(handle_unknown="ignore",sparse_output=False)
new_data = encoder.fit_transform(data)
new_data

array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1.]])

# Label Encoding

In [27]:
data.degree

0       phd
1    m.tech
2    b.tech
3       phd
4    m.tech
Name: degree, dtype: object

In [31]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
encoded_degree = le.fit_transform(data.degree)
encoded_degree


array([2, 1, 0, 2, 1])

In [32]:
data.degree #getting B.tech as 0

0       phd
1    m.tech
2    b.tech
3       phd
4    m.tech
Name: degree, dtype: object

# Not suitable in these situations

In [34]:
data.categories

0    a
1    b
2    c
3    d
4    e
Name: categories, dtype: object

In [35]:
encoded_categories = le.fit_transform(data.categories)
encoded_categories

array([0, 1, 2, 3, 4])

In [36]:
data.gender

0    m
1    f
2    m
3    f
4    f
Name: gender, dtype: object

In [37]:
encoded_gender = le.fit_transform(data.gender)
encoded_gender

array([1, 0, 1, 0, 0])

# Get Dummies

# Just Like One Hot Encoding

In [38]:
data.gender

0    m
1    f
2    m
3    f
4    f
Name: gender, dtype: object

In [39]:
pd.get_dummies(data.gender)

f  m
0  0  1
1  1  0
2  0  1
3  1  0
4  1  0

In [40]:
pd.get_dummies(data.gender,drop_first=True)

m
0  1
1  0
2  1
3  0
4  0

In [41]:
pd.get_dummies(data.categories)

a  b  c  d  e
0  1  0  0  0  0
1  0  1  0  0  0
2  0  0  1  0  0
3  0  0  0  1  0
4  0  0  0  0  1

In [42]:
pd.get_dummies(data.categories,drop_first=True)

b  c  d  e
0  0  0  0  0
1  1  0  0  0
2  0  1  0  0
3  0  0  1  0
4  0  0  0  1

# Mapping

In [43]:
data

categories gender  degree  number
0          a      m     phd       3
1          b      f  m.tech       4
2          c      m  b.tech       3
3          d      f     phd       4
4          e      f  m.tech       5

# Nominal Data
list(map(lambda x:0 if x=="m"else 1, data.gender))

In [46]:
list(map(lambda x:0 if x=="m"else 1, data.gender))
data.gender = list(map(lambda x:0 if x=="m"else 1, data.gender))
data                   

categories  gender  degree  number
0          a       0     phd       3
1          b       1  m.tech       4
2          c       0  b.tech       3
3          d       1     phd       4
4          e       1  m.tech       5

# Ordinal Data

In [51]:
data.degree.replace({"phd":3, "m.tech":2, "b.tech":1})

0    3
1    2
2    1
3    3
4    2
Name: degree, dtype: int64

In [52]:
data.degree = data.degree.replace({"phd":3, "m.tech":2, "b.tech":1})

In [53]:
data

categories  gender  degree  number
0          a       0       3       3
1          b       1       2       4
2          c       0       1       3
3          d       1       3       4
4          e       1       2       5